import home from "../imagenes/home.png";
import peliSerie from "../imagenes/PeliSerie.png";
import perfil from "../imagenes/perfil.png";
import animales from "../imagenes/animales.jpg";
import atrapad from "../imagenes/atrapad.webp";
import BlackMirror from "../imagenes/BlackMirror.jpg";
import breakingBad from "../imagenes/breakingBad.webp";
import campana3 from "../imagenes/campana3.png";
import Conclave from "../imagenes/Conclave.jpg";
import constantine from "../imagenes/constantine.jpg";
import corazon3 from "../imagenes/corazon3.png";
import corazon4 from "../imagenes/corazon4.png";
import deadpool from "../imagenes/deadpool.jpg";
import derecha from "../imagenes/derecha.png";
import DestinoFinal from "../imagenes/DestinoFinal.jpg";
import Dune2 from "../imagenes/Dune2.jpg";
import eternauta from "../imagenes/eternauta.jpeg";
import faviconP from "../imagenes/faviconP.png";
import Formula1 from "../imagenes/Formula1.jpg";
import FotoPerfil from "../imagenes/FotoPerfil.png";
import GIINYPORT from "../imagenes/GIINYPORT.jpg";
import grey from "../imagenes/grey.webp";
import implacable from "../imagenes/implacable.webp";
import izquierda from "../imagenes/izquierda.png";
import lilo2 from "../imagenes/lilo2.webp";
import LosSimpsons from "../imagenes/LosSimpsons.jpg";
import lupa from "../imagenes/lupa.png";
import marioBros from "../imagenes/marioBros.jpg";
import MisionImposible from "../imagenes/MisionImposible.jpg";
import Motorheads from "../imagenes/Motorheads.jpg";
import pure from "../imagenes/pure.JPG";
import saul from "../imagenes/saul.jpg";
import Severance from "../imagenes/Severance.jpg";
import simpsons from "../imagenes/simpsons.webp";
import Sirens from "../imagenes/Sirens.jpg";
import stranger from "../imagenes/stranger.jpg";
import TedLasso from "../imagenes/TedLasso.jpg";
import TheBear from "../imagenes/TheBear.jpg";
import TheRookie from "../imagenes/TheRookie.jpg";
import toyStory2 from "../imagenes/toyStory2.webp";
import Wicked from "../imagenes/Wicked.jpg";
import Wonka from "../imagenes/Wonka.jpg";
import YellowJackets from "../imagenes/YellowJackets.jpg";
import You from "../imagenes/You.jpg";

const ImagenGenerica = ({ imagen }) => {
  let x;
  if (imagen === "home") x = home;
  else if (imagen === "peliSerie") x = peliSerie;
  else if (imagen === "perfil") x = perfil;
  else if (imagen === "animales") x = animales;
  else if (imagen === "atrapad") x = atrapad;
  else if (imagen === "BlackMirror") x = BlackMirror;
  else if (imagen === "breakingBad") x = breakingBad;
  else if (imagen === "campana3") x = campana3;
  else if (imagen === "Conclave") x = Conclave;
  else if (imagen === "constantine") x = constantine;
  else if (imagen === "corazon3") x = corazon3;
  else if (imagen === "corazon4") x = corazon4;
  else if (imagen === "deadpool") x = deadpool;
  else if (imagen === "derecha") x = derecha;
  else if (imagen === "DestinoFinal") x = DestinoFinal;
  else if (imagen === "Dune2") x = Dune2;
  else if (imagen === "eternauta") x = eternauta;
  else if (imagen === "faviconP") x = faviconP;
  else if (imagen === "Formula1") x = Formula1;
  else if (imagen === "FotoPerfil") x = FotoPerfil;
  else if (imagen === "GIINYPORT") x = GIINYPORT;
  else if (imagen === "grey") x = grey;
  else if (imagen === "implacable") x = implacable;
  else if (imagen === "izquierda") x = izquierda;
  else if (imagen === "lilo2") x = lilo2;
  else if (imagen === "LosSimpsons") x = LosSimpsons;
  else if (imagen === "lupa") x = lupa;
  else if (imagen === "marioBros") x = marioBros;
  else if (imagen === "MisionImposible") x = MisionImposible;
  else if (imagen === "Motorheads") x = Motorheads;
  else if (imagen === "pure") x = pure;
  else if (imagen === "saul") x = saul;
  else if (imagen === "Severance") x = Severance;
  else if (imagen === "simpsons") x = simpsons;
  else if (imagen === "Sirens") x = Sirens;
  else if (imagen === "stranger") x = stranger;
  else if (imagen === "TedLasso") x = TedLasso;
  else if (imagen === "TheBear") x = TheBear;
  else if (imagen === "TheRookie") x = TheRookie;
  else if (imagen === "toyStory2") x = toyStory2;
  else if (imagen === "Wicked") x = Wicked;
  else if (imagen === "Wonka") x = Wonka;
  else if (imagen === "YellowJackets") x = YellowJackets;
  else if (imagen === "You") x = You;
  else if (imagen === "FotoPerfil") x = FotoPerfil;

  return (
    <div>
      <img src={x} />
    </div>
  );
};

export default ImagenGenerica;
